DROP DATABASE IF EXISTS USERMANAGEMENT;
CREATE DATABASE USERMANAGEMENT;
USE USERMANAGEMENT;

CREATE TABLE USER(
  ID int not null AUTO_INCREMENT,
  NAME VARCHAR (100) NOT NULL,
  GENDER CHAR (32) NULL DEFAULT NULL,
  EMAIL VARCHAR(100) NULL DEFAULT NULL,
  AGE INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (ID)
);