DROP DATABASE IF EXISTS USERMANAGEMENT;
CREATE DATABASE USERMANAGEMENT;
USE USERMANAGEMENT;

CREATE TABLE USER(
  NAME VARCHAR (100) NOT NULL,
  GENDER CHAR (32) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  AGE INTEGER NOT NULL
);